//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public string Student_N_Number { get; set; }
        public string Term { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Hours { get; set; }
        public string Description { get; set; }
        public string AuthorizedBy { get; set; }
        public string EnteredBy { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
