//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ActivityItem
    {
        public int ActivityID { get; set; }
        public string Student_N_Number { get; set; }
        public string Term { get; set; }

        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime, ErrorMessage = "Please enter a valid date in the format mm/dd/yyy")]
        public Nullable<System.DateTime> Date { get; set; }

        [Range(0, 99.99)]
        [Column(TypeName = "decimal(4, 2)")]
        public Nullable<decimal> Hours { get; set; }
        public string Description { get; set; }

        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}


